export const FETCH_URL_ITEMS = "https://serversmartphonehieu.herokuapp.com/";
// export const SHEET_BEST_PC = "https://sheet.best/api/sheets/00588ee3-7498-4b08-983d-2c4cf8e242dd"; // GLLM 
// export const SHEET_BEST_PC_LED = "https://sheet.best/api/sheets/346450cc-ce04-4d4f-9c8e-1e35777e2141"; // led
// export const SHEET_BEST_PC_SILICON = "https://sheet.best/api/sheets/a6626440-fdcc-41a2-9779-ae2b35a7767a"; //silicon

export const SHEET_BEST_PC_GLLM_RETURN = "https://sheet.best/api/sheets/a6f98e3c-1c5a-4a95-a69d-8e866511f3e5"; //Gllm return


// export const TRACKINGMORE_KEY = "febd481b-51b5-4387-96a2-aa1c865e96d4";
// export const GET_TRACKINGMORE_API = "https://cors-anywhere.herokuapp.com/http://api.trackingmore.com/v2/trackings/get";

export const STATE_POST_TO_DEFAULT = "STATE_POST_TO_DEFAULT";
export const SET_STATE_STORE_TO_DEFAULT = "SET_STATE_STORE_TO_DEFAULT";


export const GET_CHECKING_REQUEST = "GET_CHECKING_REQUEST";
export const GET_CHECKING_SUCSESS = "GET_CHECKING_SUCSESS";
export const GET_CHECKING_RFAILURE = "GET_CHECKING_RFAILURE";

export const GET_CHECKING_DATE_REQUEST = "GET_CHECKING_DATE_REQUEST";
export const GET_CHECKING_DATE_SUCSESS = "GET_CHECKING_DATE_SUCSESS";


export const GET_CI_CHECKING_REQUEST = "GET_CI_CHECKING_REQUEST";
export const GET_CI_CHECKING_SUCSESS = "GET_CI_CHECKING_SUCSESS";
export const GET_CI_CHECKING_RFAILURE = "GET_CI_CHECKING_RFAILURE";

export const CI_PATCH_ITEMS_REQUEST = "CI_PATCH_ITEMS_REQUEST";
export const CI_PATCH_ITEMS_SUCSESS = "CI_PATCH_ITEMS_SUCSESS";
export const CI_PATCH_ITEMS_RFAILURE = "CI_PATCH_ITEMS_RFAILURE";

export const CI_UPDATE_PC_PRO_REQUEST = "CI_UPDATE_PC_PRO_REQUEST";
export const CI_UPDATE_PC_PRO_SUCSESS = "CI_UPDATE_PC_PRO_SUCSESS";
export const CI_UPDATE_PC_PRO_RFAILURE = "CI_UPDATE_PC_PRO_RFAILURE";


export const CI_DELETE_ITEMS_REQUEST = "CI_DELETE_ITEMS_REQUEST";
export const CI_DELETE_ITEMS_SUCSESS = "CI_DELETE_ITEMS_SUCSESS";
export const CI_DELETE_ITEMS_RFAILURE = "CI_DELETE_ITEMS_RFAILURE";

export const POST_ITEM_EXCEL_REQUEST = "POST_ITEM_EXCEL_REQUEST";
export const POST_ITEM_EXCEL_SUCSESS = "POST_ITEM_EXCEL_SUCSESS";
export const POST_ITEM_EXCEL_RFAILURE = "POST_ITEM_EXCEL_RFAILURE";

export const GET_SHEET_PHONE_REQUEST = "GET_SHEET_PHONE_REQUEST";
export const GET_SHEET_PHONE_SUCSESS = "GET_SHEET_PHONE_SUCSESS";
export const GET_SHEET_PHONE_RFAILURE = "GET_SHEET_PHONE_RFAILURE";


export const PATCH_ITEM_EXCEL_FAIL_REQUEST = "PATCH_ITEM_EXCEL_FAIL_REQUEST";
export const PATCH_ITEM_EXCEL_FAIL_SUCSESS = "PATCH_ITEM_EXCEL_FAIL_SUCSESS";
export const PATCH_ITEM_EXCEL_FAIL_RFAILURE = "PATCH_ITEM_EXCEL_FAIL_RFAILURE";


export const CHANGE_PRINT_STATUS_REQUEST = "CHANGE_PRINT_STATUS_REQUEST";
export const CHANGE_PRINT_STATUS_SUCSESS = "CHANGE_PRINT_STATUS_SUCSESS";
export const CHANGE_PRINT_STATUS_RFAILURE = "CHANGE_PRINT_STATUS_RFAILURE";

export const PATCH_ITEM_CHECKING_PROPERTIES_REQUEST = "PATCH_ITEM_CHECKING_PROPERTIES_REQUEST";
export const PATCH_ITEM_CHECKING_PROPERTIES_SUCSESS = "PATCH_ITEM_CHECKING_PROPERTIES_SUCSESS";
export const PATCH_ITEM_CHECKING_PROPERTIES_RFAILURE = "PATCH_ITEM_CHECKING_PROPERTIES_RFAILURE";

export const DELETE_ITEM_CHECKING_REQUEST = "DELETE_ITEM_CHECKING_REQUEST";
export const DELETE_ITEM_CHECKING_SUCSESS = "DELETE_ITEM_CHECKING_SUCSESS";
export const DELETE_ITEM_CHECKING_RFAILURE = "DELETE_ITEM_CHECKING_RFAILURE";

export const ITEMS_GET_SHEET_PC_REQUEST = "ITEMS_GET_SHEET_PC_REQUEST";
export const ITEMS_GET_SHEET_PC_SUCSESS = "ITEMS_GET_SHEET_PC_SUCSESS";
export const ITEMS_GET_SHEET_PC_RFAILURE = "ITEMS_GET_SHEET_PC_RFAILURE";

export const ITEMS_GET_PC_RETURN_REQUEST = "ITEMS_GET_PC_RETURN_REQUEST";
export const ITEMS_GET_PC_RETURN_SUCSESS = "ITEMS_GET_PC_RETURN_SUCSESS";
export const ITEMS_GET_PC_RETURN_RFAILURE = "ITEMS_GET_PC_RETURN_RFAILURE";



export const ITEM_POST_ITEM_REQUEST = "ITEM_POST_ITEM_REQUEST";
export const ITEM_POST_ITEM_SUCSESS = "ITEM_POST_ITEM_SUCSESS";
export const ITEM_POST_ITEM_RFAILURE = "ITEM_POST_ITEM_RFAILURE";


export const ITEM_UPDATE_PC_PRO_REQUEST = "ITEM_UPDATE_PC_PRO_REQUEST";
export const ITEM_UPDATE_PC_PRO_RFAILURE = "ITEM_UPDATE_PC_PRO_RFAILURE";


export const ITEM_GET_PC_PRO_REQUEST = "ITEM_GET_PC_PRO_REQUEST";
export const ITEM_GET_PC_PRO_SUCSESS = "ITEM_GET_PC_PRO_SUCSESS";
export const ITEM_GET_PC_PRO_RFAILURE = "ITEM_GET_PC_PRO_RFAILURE";

export const ITEMS_PRINT_FALSE_REQUEST = "ITEMS_PRINT_FALSE_REQUEST";
export const ITEMS_PRINT_FALSE_SUCSESS = "ITEMS_PRINT_FALSE_SUCSESS";
export const ITEMS_PRINT_FALSE_RFAILURE = "ITEMS_PRINT_FALSE_RFAILURE";

export const GET_LIST_BY_ID_REQUEST = "GET_LIST_BY_ID_REQUEST";
export const GET_LIST_BY_ID_SUCSESS = "GET_LIST_BY_ID_SUCSESS";

export const GET_LIST_RFAILURE = "GET_LIST_RFAILURE";

export const POST_LIST_ITEM_COUNT_REQUEST = "POST_LIST_ITEM_COUNT_REQUEST";
export const POST_LIST_ITEM_COUNT_SUCSESS = "POST_LIST_ITEM_COUNT_SUCSESS";
export const POST_LIST_ITEM_COUNT_RFAILURE = "POST_LIST_ITEM_COUNT_RFAILURE";

export const PATCH_LIST_ITEM_COUNT_REQUEST = "PATCH_LIST_ITEM_COUNT_REQUEST";
export const PATCH_LIST_ITEM_COUNT_SUCSESS = "PATCH_LIST_ITEM_COUNT_SUCSESS";
export const PATCH_LIST_ITEM_COUNT_RFAILURE = "PATCH_LIST_ITEM_COUNT_RFAILURE";

export const POST_LIST_ITEM_COUNT_PATCH_FAIL_REQUEST = "POST_LIST_ITEM_COUNT_PATCH_FAIL_REQUEST";
export const POST_LIST_ITEM_COUNT_PATCH_FAIL_SUCSESS = "POST_LIST_ITEM_COUNT_PATCH_FAIL_SUCSESS";
export const POST_LIST_ITEM_COUNT_PATCH_FAIL_RFAILURE = "POST_LIST_ITEM_COUNT_PATCH_FAIL_RFAILURE";

export const GET_LAST_ITEM_OF_LIST_ITEM_COUNT_REQUEST = "GET_LAST_ITEM_OF_LIST_ITEM_COUNT_REQUEST";
export const GET_LAST_ITEM_OF_LIST_ITEM_COUNT_SUCSESS = "GET_LAST_ITEM_OF_LIST_ITEM_COUNT_SUCSESS";
export const GET_LAST_ITEM_OF_LIST_ITEM_COUNT_RFAILURE = "GET_LAST_ITEM_OF_LIST_ITEM_COUNT_RFAILURE";

export const PATCH_ITEM_TRACKING_CONTROL_REQUEST = "PATCH_ITEM_TRACKING_CONTROL_REQUEST";
export const PATCH_ITEM_TRACKING_CONTROL_SUCSESS = "PATCH_ITEM_TRACKING_CONTROL_SUCSESS";
export const PATCH_ITEM_TRACKING_CONTROL_RFAILURE = "PATCH_ITEM_TRACKING_CONTROL_RFAILURE";

export const GET_ITEM_TRACKING_FAIL_REQUEST = "GET_ITEM_TRACKING_FAIL_REQUEST";
export const GET_ITEM_TRACKING_FAIL_SUCSESS = "GET_ITEM_TRACKING_FAIL_SUCSESS";
export const GET_ITEM_TRACKING_FAIL_RFAILURE = "GET_ITEM_TRACKING_FAIL_RFAILURE";

export const POST_LIST_TRACKING_COUNT_REQUEST = "POST_LIST_TRACKING_COUNT_REQUEST";
export const POST_LIST_TRACKING_COUNT_SUCSESS = "POST_LIST_TRACKING_COUNT_SUCSESS";
export const POST_LIST_TRACKING_COUNT_RFAILURE = "POST_LIST_TRACKING_COUNT_RFAILURE";

export const GET_TRACKING_REQUEST = "GET_TRACKING_REQUEST";
export const GET_TRACKING_SUCSESS = "GET_TRACKING_SUCSESS";
export const GET_TRACKING_RFAILURE = "GET_TRACKING_RFAILURE";

export const GET_TRACKING_MORE_REQUEST = "GET_TRACKING_MORE_REQUEST";
export const GET_TRACKING_MORE_SUCSESS = "GET_TRACKING_MORE_SUCSESS";
export const GET_TRACKING_MORE_RFAILURE = "GET_TRACKING_MORE_RFAILURE";



export const GET_ONE_TRACKING_REQUEST = "GET_ONE_TRACKING_REQUEST";
export const GET_ONE_TRACKING_SUCSESS = "GET_ONE_TRACKING_SUCSESS";
export const GET_ONE_TRACKING_RFAILURE = "GET_ONE_TRACKING_RFAILURE";

export const GET_USE_INFO_REQUEST = "GET_USE_INFO_REQUEST";
export const GET_USE_INFO_SUCSESS = "GET_USE_INFO_SUCSESS";
export const GET_USE_INFO_RFAILURE = "GET_USE_INFO_RFAILURE";

export const STATE_USER_TO_DEFAULT = "STATE_USER_TO_DEFAULT";

export const GET_LIST_USER_REQUEST = "GET_LIST_USER_REQUEST";
export const GET_LIST_USER_SUCSESS = "GET_LIST_USER_SUCSESS";
export const GET_LIST_USER_RFAILURE = "GET_LIST_USER_RFAILURE";

export const USER_GET_LIST_BY_ID_REQUEST = "USER_GET_LIST_BY_ID_REQUEST";
export const USER_GET_LIST_BY_ID_SUCSESS = "USER_GET_LIST_BY_ID_SUCSESS";
export const USER_GET_LIST_BY_ID_RFAILURE = "USER_GET_LIST_BY_ID_RFAILURE";


export const CHANGE_USE_PROPERTIES_REQUEST = "CHANGE_USE_PROPERTIES_REQUEST";
export const CHANGE_USE_PROPERTIES_SUCSESS = "CHANGE_USE_PROPERTIES_SUCSESS";
export const CHANGE_USE_PROPERTIES_RFAILURE = "CHANGE_USE_PROPERTIES_RFAILURE";


export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCSESS = "CREATE_USER_SUCSESS";
export const CREATE_USER_RFAILURE = "CREATE_USER_RFAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCSESS = "DELETE_USER_SUCSESS";
export const DELETE_USER_RFAILURE = "DELETE_USER_RFAILURE";

export const EXCEL_GET_LIST_BY_ID_REQUEST = "EXCEL_GET_LIST_BY_ID_REQUEST";
export const EXCEL_GET_LIST_BY_ID_SUCSESS = "EXCEL_GET_LIST_BY_ID_SUCSESS";
export const EXCEL_GET_LIST_BY_ID_RFAILURE = "EXCEL_GET_LIST_BY_ID_RFAILURE";

export const GET_ORDER_BY_DAY_REQUEST = "GET_ORDER_BY_DAY_REQUEST";
export const GET_ORDER_BY_DAY_SUCSESS = "GET_ORDER_BY_DAY_SUCSESS";
export const GET_RFAILURE = "GET_RFAILURE";


export const STATE_STORE_TRACKING_TO_DEFAULT = "STATE_STORE_TRACKING_TO_DEFAULT";

export const PUT_USER_REQUEST = "PUT_USER_REQUEST";
export const PUT_USER_SUCSESS = "PUT_USER_SUCSESS";
export const PUT_USER_RFAILURE = "PUT_USER_RFAILURE";


export const GET_SUM_ITEM_REQUEST = "GET_SUM_ITEM_REQUEST";
export const GET_SUM_ITEM_SUCSESS = "GET_SUM_ITEM_SUCSESS";
export const GET_HOME_RFAILURE = "GET_HOME_RFAILURE";


export const STATE_STORE_HOME_TO_DEFAULT = "STATE_STORE_HOME_TO_DEFAULT";
export const PROPS_ITEMS_TO_DEFAULT = "PROPS_ITEMS_TO_DEFAULT";
export const PROPS_CONTROL_ITEMS_TO_DEFAULT = "PROPS_CONTROL_ITEMS_TO_DEFAULT";


export const GET_LAST_ITEM_REQUEST = "GET_LAST_ITEM_REQUEST";
export const GET_LAST_ITEM_SUCSESS = "GET_LAST_ITEM_SUCSESS";
